"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Lambda function to check if a stringified boolean-like variable is true
truly = lambda x: x == '1' or x == 'True'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-man+)nj-6n5d%hwi-x@%))bnubq2i=e9yn6m_#8**t-frot)cn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # truly(os.getenv('APP_DEBUG', 'False'))
LOCAL = truly(os.getenv('APP_LOCAL', 'True'))

# Choose DB (use sqlite otherwise)
USE_LOCAL_DB = truly(os.getenv('USE_LOCAL_DB', 'False'))
USE_POSTGRES = truly(os.getenv('USE_POSTGRES', 'False'))
USE_MYSQL = truly(os.getenv('USE_MYSQL', 'False'))

ALLOWED_HOSTS = [
    "demo.lilliputten.ru",
    "test.demo.lilliputten.ru",
    "initial.demo.lilliputten.ru",
    "localhost",
]
#  CSRF_TRUSTED_ORIGINS = ["http://demo.lilliputten.ru.xsph.ru"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # "django.contrib.postgres", # Required by Django v.6; may cause 5xx server error on sprinthost
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR.parent / "public_html/static"


# Database

elif USE_LOCAL_DB:
    # Local PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'zdkv-test',
            'USER': 'postgres',
            'PASSWORD': '1',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }
elif USE_POSTGRES:
    # Server PostgreSQL
    DATABASES = {
       'default': {
           'ENGINE': 'django.db.backends.postgresql',
           'NAME': 's1149038_zdkv',
           'USER': 's1149038_zdkv',
           'PASSWORD': 'kihiiwisud',
           'HOST': 'localhost',
           # 'PORT': '5432',
       }
    }
elif USE_MYSQL:
    # Initial MySQL/MariaDB
    import pymysql
    pymysql.version_info=(2, 2, 7, "final", 0)
    pymysql.install_as_MySQLdb()
    DATABASES = {
        'default': {
            "ENGINE": "django.db.backends.mysql",
            "NAME": "s1149038_app_django_2",
            "USER": "s1149038_app_django_2",
            "PASSWORD": "N86ZHpP0RL",
            "HOST": "localhost",
            "OPTIONS": {
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            }
        }
    }
else:
    # SQLite3
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

